server:
  port: 9000

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.10:3306/gulimall_oms?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: gulimall-order
  #    nacos注册中心地址配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  # rabbitmq配置，消息确认机制配置在application.properties
  rabbitmq:
    host: 192.168.50.10
    port: 5672
    virtual-host: /

  redis:
    host: 192.168.50.10
    port: 6379
    password: redis


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
#   分配ID(主键类型为Number(Long和Integer)或String)(since 3.3.0),
#  使用接口IdentifierGenerator的方法nextId
#  (默认实现类为DefaultIdentifierGenerator雪花算法)
      id-type: auto


# 线程池配置
thread:
  pool:
    config:
      core-size: 20
      maximum-size: 200
      keep-alive-time: 10
      block-queue-size: 10000
